# Generated by Django 6.0 on 2025-12-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="currency",
            field=models.CharField(
                choices=[("usd", "USD"), ("eur", "EUR")], default="usd", max_length=3
            ),
        ),
    ]
